
title: Osman faruk bayram
email: osmanfbayram@gmail.com

first_name: osman
middle_name: faruk
last_name: bayram

icon: fa glasses
description: Osman faruk bayram's personal blog

twitter_username: the_osbm
github_username:  osbm

theme: minima
#baseurl: "" 
#url: ""
