
title: Osman faruk bayram
email: osmanfbayram@gmail.com

first_name: osman
middle_name: faruk
last_name: bayram

icon: fa glasses
description: Osman faruk bayram's personal blog

twitter_username: the_osbm
github_username:  osbm
linkedin_username: osbm


theme: minima
#baseurl: "" 
#url: ""

navbar_fixed: true
footer_fixed: true

max_width: 1200px

contact_note: >
  Feel free to reach out!


markdown: kramdown


enable_darkmode: true
